# Generated by Django 4.0.1 on 2022-01-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_delete_comments'),
        ('discuss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('fop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='first.food')),
            ],
        ),
    ]
