# Generated by Django 4.0.1 on 2022-01-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_delete_comments'),
        ('discuss', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.food'),
        ),
    ]
