# Generated by Django 4.0.1 on 2022-01-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_order_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
